In [27]:
# In this notebook we will try to solve the prolem of overfitting by using L1 and L2 regularization technique.
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv('Melbourne_housing.csv')
df

C:\Users\sorre\AppData\Local\Temp\ipykernel_24960\1321220460.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Melbourne_housing.csv')

,Suburb,Address,Rooms,Type,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Latitude,Longtitude,Regionname,Propertycount,ParkingArea,Price
0,Abbotsford,68 Studley St,2,h,SS,Jellis,3/9/2016,2.5,3067.0,2.0,...,126.0,inf,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0,Carport,NaN
1,Airport West,154 Halsey Rd,3,t,PI,Nelson,3/9/2016,13.5,3042.0,3.0,...,303.0,225,2016.0,Moonee Valley City Council,-37.71800,144.87800,Western Metropolitan,3464.0,Detached Garage,840000.0
2,Albert Park,105 Kerferd Rd,2,h,S,hockingstuart,3/9/2016,3.3,3206.0,2.0,...,120.0,82,1900.0,Port Phillip City Council,-37.84590,144.95550,Southern Metropolitan,3280.0,Attached Garage,1275000.0
3,Albert Park,85 Richardson St,2,h,S,Thomson,3/9/2016,3.3,3206.0,2.0,...,159.0,inf,NaN,Port Phillip City Council,-37.84500,144.95380,Southern Metropolitan,3280.0,Indoor,1455000.0
4,Alphington,30 Austin St,3,h,SN,McGrath,3/9/2016,6.4,3078.0,3.0,...,174.0,122,2003.0,Darebin City Council,-37.78180,145.01980,Northern Metropolitan,2211.0,Parkade,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Reservoir,18 Elinda Pl,3,u,SP,RW,30/09/2017,12.0,3073.0,3.0,...,NaN,105.0,1990.0,Darebin City Council,-37.69769,145.02332,Northern Metropolitan,21650.0,Parkade,475000.0
34853,Roxburgh Park,14 Stainsby Cr,4,h,S,Raine,30/09/2017,20.6,3064.0,4.0,...,NaN,225.0,1995.0,Hume City Council,-37.63665,144.92976,Northern Metropolitan,5833.0,Underground,591000.0
34854,Springvale South,8 Bellbird Ct,4,h,PI,Barry,30/09/2017,22.2,3172.0,4.0,...,534.0,152.0,1970.0,Greater Dandenong City Council,-37.97037,145.15449,South-Eastern Metropolitan,4054.0,Carport,NaN
34855,Springvale South,30 Waddington Cr,3,h,S,Harcourts,30/09/2017,22.2,3172.0,3.0,...,544.0,NaN,NaN,Greater Dandenong City Council,-37.97751,145.14813,South-Eastern Metropolitan,4054.0,Detached Garage,780500.0
34856,Westmeadows,42 Pascoe St,4,h,S,Barry,30/09/2017,16.5,3049.0,4.0,...,813.0,140.0,1960.0,Hume City Council,-37.67631,144.89409,Northern Metropolitan,2474.0,Attached Garage,791000.0

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Method         34857 non-null  object
 5   SellerG        34857 non-null  object
 6   Date           34857 non-null  object
 7   Distance       34856 non-null  float64
 8   Postcode       34856 non-null  float64
 9   Bedroom        26640 non-null  float64
 10  Bathroom       26631 non-null  float64
 11  Car            26129 non-null  float64
 12  Landsize       23047 non-null  float64
 13  BuildingArea   13760 non-null  object
 14  YearBuilt      15551 non-null  float64
 15  CouncilArea    34854 non-null  object
 16  Latitude       26881 non-null  float64
 17  Longtitude     26881 non-null  float64
 18  Regionname     34857 non-null  object
 19  Propertycount  34854 non-null  float64
 20  ParkingArea    34857 non-null  object
 21  Price          27247 non-null  float64
dtypes: float64(11), int64(1), object(10)
memory usage: 5.9+ MB

In [30]:
df.describe()

,Rooms,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,YearBuilt,Latitude,Longtitude,Propertycount,Price
count,34857.000000,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,15551.000000,26881.000000,26881.000000,34854.000000,2.724700e+04
mean,3.031012,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,1965.289885,-37.810634,145.001851,7572.888306,1.050173e+06
std,0.969933,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,37.328178,0.090279,0.120169,4428.090313,6.414671e+05
min,1.000000,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.190430,144.423790,83.000000,8.500000e+04
25%,2.000000,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,1940.000000,-37.862950,144.933500,4385.000000,6.350000e+05
50%,3.000000,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,1970.000000,-37.807600,145.007800,6763.000000,8.700000e+05
75%,4.000000,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,2000.000000,-37.754100,145.071900,10412.000000,1.295000e+06
max,16.000000,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,2106.000000,-37.390200,145.526350,21650.000000,1.120000e+07

In [31]:
#PULIZIA DATI MANCANTI E ANOMALI

# Sostituisco valori infiniti con NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)


# Controllo se ci sono ancora valori mancanti
print("Valori mancanti per colonna:")
print(df.isnull().sum())

# Converte le colonne in numerico
df[["Landsize", "BuildingArea", "Price"]] = df[["Landsize", "BuildingArea", "Price"]].apply(pd.to_numeric, errors="coerce")

#Controlla se ci sono outlier nelle colonne più critiche ed eventualmente le rimuove
cols_to_check = ["Landsize", "BuildingArea", "Price"]

for col in cols_to_check:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    mask = (df[col] < lower_bound) | (df[col] > upper_bound)
    df = df[~mask]

df.head()

Valori mancanti per colonna:
Suburb               0
Address              0
Rooms                0
Type                 0
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom           8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21097
YearBuilt        19306
CouncilArea          3
Latitude          7976
Longtitude        7976
Regionname           0
Propertycount        3
ParkingArea          0
Price             7610
dtype: int64

,Suburb,Address,Rooms,Type,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Latitude,Longtitude,Regionname,Propertycount,ParkingArea,Price
1,Airport West,154 Halsey Rd,3,t,PI,Nelson,3/9/2016,13.5,3042.0,3.0,...,303.0,225.0,2016.0,Moonee Valley City Council,-37.7180,144.8780,Western Metropolitan,3464.0,Detached Garage,840000.0
2,Albert Park,105 Kerferd Rd,2,h,S,hockingstuart,3/9/2016,3.3,3206.0,2.0,...,120.0,82.0,1900.0,Port Phillip City Council,-37.8459,144.9555,Southern Metropolitan,3280.0,Attached Garage,1275000.0
4,Alphington,30 Austin St,3,h,SN,McGrath,3/9/2016,6.4,3078.0,3.0,...,174.0,122.0,2003.0,Darebin City Council,-37.7818,145.0198,Northern Metropolitan,2211.0,Parkade,NaN
5,Alphington,6 Smith St,4,h,S,Brace,3/9/2016,6.4,3078.0,3.0,...,853.0,263.0,1930.0,Darebin City Council,-37.7707,145.0318,Northern Metropolitan,2211.0,Underground,2000000.0
7,Altona,158 Queen St,3,h,VB,Greg,3/9/2016,13.8,3018.0,3.0,...,352.0,242.0,2015.0,Hobsons Bay City Council,-37.8700,144.8250,Western Metropolitan,5301.0,Parking Pad,520000.0

In [32]:
df.nunique()

Suburb             342
Address          31779
Rooms               11
Type                 3
Method               9
SellerG            381
Date                78
Distance           213
Postcode           207
Bedroom             14
Bathroom            10
Car                 13
Landsize          1190
BuildingArea       475
YearBuilt          151
CouncilArea         33
Latitude         12731
Longtitude       13833
Regionname           8
Propertycount      334
ParkingArea          8
Price             2433
dtype: int64

In [33]:
df.shape

(32511, 22)

In [34]:
df.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom           8010
Bathroom          8017
Car               8490
Landsize         11405
BuildingArea     20107
YearBuilt        18380
CouncilArea          3
Latitude          7776
Longtitude        7776
Regionname           0
Propertycount        3
ParkingArea          0
Price             7274
dtype: int64

In [35]:
# now lets observe our data and try to drop some columns that are not very uselful in our data analysis. I am just dropping some columns
# like date, latitute etc that are not very meaningful for our analysis. 
columns_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount', 'Distance', 'CouncilArea', 'Bedroom', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']
df_new = df[columns_to_use]
df_new

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom,Bathroom,Car,Landsize,BuildingArea,Price
1,Airport West,3,t,PI,Nelson,Western Metropolitan,3464.0,13.5,Moonee Valley City Council,3.0,2.0,1.0,303.0,225.0,840000.0
2,Albert Park,2,h,S,hockingstuart,Southern Metropolitan,3280.0,3.3,Port Phillip City Council,2.0,1.0,0.0,120.0,82.0,1275000.0
4,Alphington,3,h,SN,McGrath,Northern Metropolitan,2211.0,6.4,Darebin City Council,3.0,2.0,1.0,174.0,122.0,NaN
5,Alphington,4,h,S,Brace,Northern Metropolitan,2211.0,6.4,Darebin City Council,3.0,2.0,4.0,853.0,263.0,2000000.0
7,Altona,3,h,VB,Greg,Western Metropolitan,5301.0,13.8,Hobsons Bay City Council,3.0,2.0,1.0,352.0,242.0,520000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Reservoir,3,u,SP,RW,Northern Metropolitan,21650.0,12.0,Darebin City Council,3.0,1.0,1.0,NaN,105.0,475000.0
34853,Roxburgh Park,4,h,S,Raine,Northern Metropolitan,5833.0,20.6,Hume City Council,4.0,2.0,2.0,NaN,225.0,591000.0
34854,Springvale South,4,h,PI,Barry,South-Eastern Metropolitan,4054.0,22.2,Greater Dandenong City Council,4.0,2.0,2.0,534.0,152.0,NaN
34855,Springvale South,3,h,S,Harcourts,South-Eastern Metropolitan,4054.0,22.2,Greater Dandenong City Council,3.0,2.0,1.0,544.0,NaN,780500.0
34856,Westmeadows,4,h,S,Barry,Northern Metropolitan,2474.0,16.5,Hume City Council,4.0,2.0,6.0,813.0,140.0,791000.0

In [36]:
df_new.shape

(32511, 15)

In [37]:
# now lets do some data cleaning
df_new.isna().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           0
Propertycount        3
Distance             1
CouncilArea          3
Bedroom           8010
Bathroom          8017
Car               8490
Landsize         11405
BuildingArea     20107
Price             7274
dtype: int64

In [38]:
# so we have several columns with NaN values so we need to handle these columns. We can actually fill some of these column's NaN 
# values just by 0 and some other columns might need some other treatment based on their nature for example price.
# lets first handle the columns where we need to fill only 0.
columns_to_fill_0 = ['Car', 'Bathroom', 'Bedroom', 'Distance', 'Propertycount']
df_new[columns_to_fill_0] = df[columns_to_fill_0].fillna(0)
df_new.isna().sum()

C:\Users\sorre\AppData\Local\Temp\ipykernel_24960\2434289955.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[columns_to_fill_0] = df[columns_to_fill_0].fillna(0)

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           0
Propertycount        0
Distance             0
CouncilArea          3
Bedroom              0
Bathroom             0
Car                  0
Landsize         11405
BuildingArea     20107
Price             7274
dtype: int64

In [39]:
# Now lets fill the columns named landsize and building area with mean of the whole respective columns
df_new['Landsize'] = pd.to_numeric(df_new['Landsize'], errors='coerce') # the numbers were in string form so had to convert them to integers.
df_new['BuildingArea'] = pd.to_numeric(df_new['BuildingArea'], errors='coerce')
df_new['Landsize'] = df_new['Landsize'].fillna(df_new.Landsize.mean())
df_new['BuildingArea'] = df_new['BuildingArea'].fillna(df_new.BuildingArea.mean())
df_new = df_new.replace([np.inf, -np.inf], np.nan).dropna()
# in the buildingArea column there are some infitly large valuea and the model was not training because of that that is why 
# I had to come back here and drop those inf values as well.

C:\Users\sorre\AppData\Local\Temp\ipykernel_24960\1726675753.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Landsize'] = pd.to_numeric(df_new['Landsize'], errors='coerce') # the numbers were in string form so had to convert them to integers.
C:\Users\sorre\AppData\Local\Temp\ipykernel_24960\1726675753.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['BuildingArea'] = pd.to_numeric(df_new['BuildingArea'], errors='coerce')
C:\Users\sorre\AppData\Local\Temp\ipykernel_24960\1726675753.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Landsize'] = df_new['Landsize'].fillna(df_new.Landsize.mean())
C:\Users\sorre\AppData\Local\Temp\ipykernel_24960\1726675753.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['BuildingArea'] = df_new['BuildingArea'].fillna(df_new.BuildingArea.mean())

In [40]:
df_new.isna().sum()

Suburb           0
Rooms            0
Type             0
Method           0
SellerG          0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
Bedroom          0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
Price            0
dtype: int64

In [41]:
# now we are good to go with out cleaned data. Now we are going to make dummy variables for our whole dataset.
df_new = pd.get_dummies(df_new, drop_first=True) # it is a short cut to avoid dummy variable trap it is just dropping the main column whose dummies we have produced. 
df_new

,Rooms,Propertycount,Distance,Bedroom,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Aberfeldie,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
1,3,3464.0,13.5,3.0,2.0,1.0,303.000000,225.000000,840000.0,False,...,False,False,False,False,False,False,False,False,False,False
2,2,3280.0,3.3,2.0,1.0,0.0,120.000000,82.000000,1275000.0,False,...,False,False,False,True,False,False,False,False,False,False
5,4,2211.0,6.4,3.0,2.0,4.0,853.000000,263.000000,2000000.0,False,...,False,False,False,False,False,False,False,False,False,False
7,3,5301.0,13.8,3.0,2.0,1.0,352.000000,242.000000,520000.0,False,...,False,False,False,False,False,False,False,False,False,False
9,5,5132.0,11.1,5.0,3.0,6.0,592.000000,251.000000,1085000.0,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34851,3,11806.0,22.7,3.0,1.0,6.0,569.000000,130.000000,627500.0,False,...,False,False,False,False,False,False,False,False,False,False
34852,3,21650.0,12.0,3.0,1.0,1.0,443.295508,105.000000,475000.0,False,...,False,False,False,False,False,False,False,False,False,False
34853,4,5833.0,20.6,4.0,2.0,2.0,443.295508,225.000000,591000.0,False,...,False,False,False,False,False,False,False,False,False,False
34855,3,4054.0,22.2,3.0,2.0,1.0,544.000000,139.754155,780500.0,False,...,False,False,False,False,False,False,False,False,False,False
34856,4,2474.0,16.5,4.0,2.0,6.0,813.000000,140.000000,791000.0,False,...,False,False,False,False,False,False,False,False,False,False

In [42]:
x = df_new.drop('Price', axis='columns')
y = df_new.Price

In [43]:
# Now we can jump into our machine learning model and lets first use the train_test_split method
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, random_state=2)

In [44]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [45]:
from sklearn.preprocessing import MinMaxScaler

#Scaling con MinMax
scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [46]:
from sklearn.metrics import mean_squared_error , r2_score



# Linear Regression con dati scalati
model.fit(x_train_scaled, y_train)
y_pred_lin = model.predict(x_test_scaled)

# Calcolo metriche
mse_lin = mean_squared_error(y_test, y_pred_lin)
rmse_lin = np.sqrt(mse_lin)
r2_lin = r2_score(y_test, y_pred_lin)

print(f"Linear Regression -> MSE: {mse_lin:.2f}, R²: {r2_lin:.2f}, RMSE: {rmse_lin:.2f}")

Linear Regression -> MSE: 47441207493.78, R²: 0.74, RMSE: 217810.03

In [47]:
model.score(x_train_scaled, y_train)

0.7530819998962813

In [48]:
from sklearn.linear_model import Lasso   


lasso_model = Lasso(alpha=50, max_iter=10000, tol=0.1)
lasso_model.fit(x_train_scaled, y_train)

y_pred_lasso = lasso_model.predict(x_test_scaled)

mse_lasso = mean_squared_error(y_test, y_pred_lasso)
rmse_lasso = np.sqrt(mse_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print(f"Lasso Regression -> MSE: {mse_lasso:.2f}, R²: {r2_lasso:.2f}, RMSE: {rmse_lasso:.2f}")

Lasso Regression -> MSE: 47206419815.74, R²: 0.74, RMSE: 217270.38

In [49]:
lasso_model.score(x_test_scaled, y_test)
# We can see that from -48 percent score to 70 percent score our model is much bette now after using L1 regularization.

0.7403067635994862

In [50]:
lasso_model.score(x_train_scaled, y_train)

0.7464372853458219

In [51]:
from sklearn.linear_model import Ridge

# Ridge Regression con dati scalati
ridge_model = Ridge(alpha=50, max_iter=10000, tol=0.1)
ridge_model.fit(x_train_scaled, y_train)

# Predizioni
y_pred_ridge = ridge_model.predict(x_test_scaled)

# Metriche
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
rmse_ridge = np.sqrt(mse_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print(f"Ridge Regression -> MSE: {mse_ridge:.2f}, R²: {r2_ridge:.2f}, RMSE: {rmse_ridge:.2f}")

Ridge Regression -> MSE: 50863161556.05, R²: 0.72, RMSE: 225528.63

In [52]:
ridge_model.score(x_test_scaled,y_test)
# after using L2 regularization our model is also much better but it seems that L1 regularization is slightly better then L2 in this case.

0.7201901968077653

In [53]:
ridge_model.score(x_train_scaled,y_train)

0.7229380503395705