In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [86]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, RidgeCV, LassoCV, Lasso, Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error as MSE
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score
from sklearn.metrics import root_mean_squared_error as RMSE

In [56]:
#lettura dati
df = pd.read_csv('Melbourne_housing.csv')
df.head(6)

C:\Users\m-rog\AppData\Local\Temp\ipykernel_29196\2770047912.py:2: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Melbourne_housing.csv')

,Suburb,Address,Rooms,Type,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Latitude,Longtitude,Regionname,Propertycount,ParkingArea,Price
0,Abbotsford,68 Studley St,2,h,SS,Jellis,3/9/2016,2.5,3067.0,2.0,...,126.0,inf,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0,Carport,NaN
1,Airport West,154 Halsey Rd,3,t,PI,Nelson,3/9/2016,13.5,3042.0,3.0,...,303.0,225,2016.0,Moonee Valley City Council,-37.7180,144.8780,Western Metropolitan,3464.0,Detached Garage,840000.0
2,Albert Park,105 Kerferd Rd,2,h,S,hockingstuart,3/9/2016,3.3,3206.0,2.0,...,120.0,82,1900.0,Port Phillip City Council,-37.8459,144.9555,Southern Metropolitan,3280.0,Attached Garage,1275000.0
3,Albert Park,85 Richardson St,2,h,S,Thomson,3/9/2016,3.3,3206.0,2.0,...,159.0,inf,NaN,Port Phillip City Council,-37.8450,144.9538,Southern Metropolitan,3280.0,Indoor,1455000.0
4,Alphington,30 Austin St,3,h,SN,McGrath,3/9/2016,6.4,3078.0,3.0,...,174.0,122,2003.0,Darebin City Council,-37.7818,145.0198,Northern Metropolitan,2211.0,Parkade,NaN
5,Alphington,6 Smith St,4,h,S,Brace,3/9/2016,6.4,3078.0,3.0,...,853.0,263,1930.0,Darebin City Council,-37.7707,145.0318,Northern Metropolitan,2211.0,Underground,2000000.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Method         34857 non-null  object
 5   SellerG        34857 non-null  object
 6   Date           34857 non-null  object
 7   Distance       34856 non-null  float64
 8   Postcode       34856 non-null  float64
 9   Bedroom        26640 non-null  float64
 10  Bathroom       26631 non-null  float64
 11  Car            26129 non-null  float64
 12  Landsize       23047 non-null  float64
 13  BuildingArea   13760 non-null  object
 14  YearBuilt      15551 non-null  float64
 15  CouncilArea    34854 non-null  object
 16  Latitude       26881 non-null  float64
 17  Longtitude     26881 non-null  float64
 18  Regionname     34857 non-null  object
 19  Propertycount  34854 non-null  float64
 20  ParkingArea    34857 non-null  object
 21  Price          27247 non-null  float64
dtypes: float64(11), int64(1), object(10)
memory usage: 5.9+ MB

In [6]:
df.describe()

,Rooms,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,YearBuilt,Latitude,Longtitude,Propertycount,Price
count,34857.000000,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,15551.000000,26881.000000,26881.000000,34854.000000,2.724700e+04
mean,3.031012,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,1965.289885,-37.810634,145.001851,7572.888306,1.050173e+06
std,0.969933,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,37.328178,0.090279,0.120169,4428.090313,6.414671e+05
min,1.000000,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.190430,144.423790,83.000000,8.500000e+04
25%,2.000000,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,1940.000000,-37.862950,144.933500,4385.000000,6.350000e+05
50%,3.000000,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,1970.000000,-37.807600,145.007800,6763.000000,8.700000e+05
75%,4.000000,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,2000.000000,-37.754100,145.071900,10412.000000,1.295000e+06
max,16.000000,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,2106.000000,-37.390200,145.526350,21650.000000,1.120000e+07

In [11]:
pd.crosstab(index=df['Type'], columns='count').reset_index()

col_0 Type  count
0        h  23980
1        t   3580
2        u   7297

In [9]:
null_fraction = (
    df.isnull()
            .mean()
            .rename("fraction_nulls")
            .to_frame()
)

print(null_fraction)

               fraction_nulls
Suburb               0.000000
Address              0.000000
Rooms                0.000000
Type                 0.000000
Method               0.000000
SellerG              0.000000
Date                 0.000000
Distance             0.000029
Postcode             0.000029
Bedroom              0.235735
Bathroom             0.235993
Car                  0.250394
Landsize             0.338813
BuildingArea         0.605244
YearBuilt            0.553863
CouncilArea          0.000086
Latitude             0.228821
Longtitude           0.228821
Regionname           0.000000
Propertycount        0.000086
ParkingArea          0.000000
Price                0.218321

In [8]:
df.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom             15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       994
YearBuilt          160
CouncilArea         33
Latitude         13402
Longtitude       14524
Regionname           8
Propertycount      342
ParkingArea          8
Price             2871
dtype: int64

In [ ]:
columns_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount', 'Distance', 'CouncilArea', 'Bedroom', 'Bathroom', 'Car', 'Landsize', 'Price','Longtitude', 'Latitude' ]
df_new = df[columns_to_use]
#df_new

In [58]:
df_new = df_new[df_new["Price"].notna()]

In [59]:
null_fraction = (
    df_new.isnull()
            .mean()
            .rename("fraction_nulls")
            .to_frame()
)

print(null_fraction)

               fraction_nulls
Suburb               0.000000
Rooms                0.000000
Type                 0.000000
Method               0.000000
SellerG              0.000000
Regionname           0.000000
Propertycount        0.000110
Distance             0.000037
CouncilArea          0.000110
Bedroom              0.236393
Bathroom             0.236613
Car                  0.250450
Landsize             0.340037
Price                0.000000

In [60]:
col_few_nulls = null_fraction[null_fraction["fraction_nulls"] < 0.1].index.tolist()
df_new.dropna(subset=col_few_nulls, inplace=True)

In [61]:
df_new['Bedroom']  = df_new['Bedroom'].fillna(df['Rooms'] // 2)
df_new['Bathroom'] = df_new['Bathroom'].fillna(df['Rooms'] // 3)
df_new['Car']      = df_new['Car'].fillna(0)
df_new['Landsize'] = df_new['Landsize'].fillna(df['Landsize'].median())

In [ ]:
df_new['Longitude']

In [62]:
null_fraction = (
    df_new.isnull()
            .mean()
            .rename("fraction_nulls")
            .to_frame()
)

print(null_fraction)

               fraction_nulls
Suburb                    0.0
Rooms                     0.0
Type                      0.0
Method                    0.0
SellerG                   0.0
Regionname                0.0
Propertycount             0.0
Distance                  0.0
CouncilArea               0.0
Bedroom                   0.0
Bathroom                  0.0
Car                       0.0
Landsize                  0.0
Price                     0.0

In [63]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27244 entries, 1 to 34856
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27244 non-null  object
 1   Rooms          27244 non-null  int64
 2   Type           27244 non-null  object
 3   Method         27244 non-null  object
 4   SellerG        27244 non-null  object
 5   Regionname     27244 non-null  object
 6   Propertycount  27244 non-null  float64
 7   Distance       27244 non-null  float64
 8   CouncilArea    27244 non-null  object
 9   Bedroom        27244 non-null  float64
 10  Bathroom       27244 non-null  float64
 11  Car            27244 non-null  float64
 12  Landsize       27244 non-null  float64
 13  Price          27244 non-null  float64
dtypes: float64(7), int64(1), object(6)
memory usage: 3.1+ MB

In [71]:
numerical_cols = df_new.select_dtypes(include=["float64","int64"]).columns

scaler = StandardScaler()

df_new[numerical_cols] = scaler.fit_transform(df_new[numerical_cols])

In [73]:
df_new

,Rooms,Propertycount,Distance,Bedroom,Bathroom,Car,Landsize,Price,Suburb_Aberfeldie,Suburb_Airport West,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
1,0.007996,-0.913292,0.326981,0.339918,0.821472,-0.251407,-0.087088,-0.327695,False,True,...,False,False,False,False,False,False,False,False,False,False
2,-1.039352,-0.954251,-1.175792,-0.500057,-0.456958,-1.130765,-0.147037,0.350424,False,False,...,False,False,False,True,False,False,False,False,False,False
3,-1.039352,-0.954251,-1.175792,-0.500057,-0.456958,-1.130765,-0.134261,0.631025,False,False,...,False,False,False,True,False,False,False,False,False,False
5,1.055344,-1.192214,-0.719067,0.339918,0.821472,2.386669,0.093086,1.480622,False,False,...,False,False,False,False,False,False,False,False,False,False
6,0.007996,-1.192214,-0.719067,0.339918,0.821472,0.627952,-0.118209,0.093206,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34851,0.007996,0.943663,1.682422,0.339918,-0.456958,4.145385,0.000051,-0.658960,False,False,...,False,False,False,False,False,False,False,False,False,False
34852,0.007996,3.134969,0.105985,0.339918,-0.456958,-0.251407,-0.015674,-0.896691,False,False,...,False,False,False,False,False,False,False,False,False,False
34853,1.055344,-0.385945,1.373028,1.179892,0.821472,0.627952,-0.015674,-0.715860,False,False,...,False,False,False,False,False,False,False,False,False,False
34855,0.007996,-0.781956,1.608757,0.339918,0.821472,-0.251407,-0.008139,-0.420449,False,False,...,False,False,False,False,False,False,False,False,False,False
34856,1.055344,-1.133669,0.768972,1.179892,0.821472,4.145385,0.079982,-0.404081,False,False,...,False,False,False,False,False,False,False,False,False,False

In [74]:
# now we are good to go with out cleaned data. Now we are going to make dummy variables for our whole dataset.
df_new = pd.get_dummies(df_new, drop_first=True) # it is a short cut to avoid dummy variable trap it is just dropping the main column whose dummies we have produced. 
df_new

,Rooms,Propertycount,Distance,Bedroom,Bathroom,Car,Landsize,Price,Suburb_Aberfeldie,Suburb_Airport West,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
1,0.007996,-0.913292,0.326981,0.339918,0.821472,-0.251407,-0.087088,-0.327695,False,True,...,False,False,False,False,False,False,False,False,False,False
2,-1.039352,-0.954251,-1.175792,-0.500057,-0.456958,-1.130765,-0.147037,0.350424,False,False,...,False,False,False,True,False,False,False,False,False,False
3,-1.039352,-0.954251,-1.175792,-0.500057,-0.456958,-1.130765,-0.134261,0.631025,False,False,...,False,False,False,True,False,False,False,False,False,False
5,1.055344,-1.192214,-0.719067,0.339918,0.821472,2.386669,0.093086,1.480622,False,False,...,False,False,False,False,False,False,False,False,False,False
6,0.007996,-1.192214,-0.719067,0.339918,0.821472,0.627952,-0.118209,0.093206,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34851,0.007996,0.943663,1.682422,0.339918,-0.456958,4.145385,0.000051,-0.658960,False,False,...,False,False,False,False,False,False,False,False,False,False
34852,0.007996,3.134969,0.105985,0.339918,-0.456958,-0.251407,-0.015674,-0.896691,False,False,...,False,False,False,False,False,False,False,False,False,False
34853,1.055344,-0.385945,1.373028,1.179892,0.821472,0.627952,-0.015674,-0.715860,False,False,...,False,False,False,False,False,False,False,False,False,False
34855,0.007996,-0.781956,1.608757,0.339918,0.821472,-0.251407,-0.008139,-0.420449,False,False,...,False,False,False,False,False,False,False,False,False,False
34856,1.055344,-1.133669,0.768972,1.179892,0.821472,4.145385,0.079982,-0.404081,False,False,...,False,False,False,False,False,False,False,False,False,False

In [75]:
y = df_new.Price
X = df_new.drop('Price', axis='columns')

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 42)

In [102]:
regression = LinearRegression()
regression.fit(X_train, y_train)
pred = regression.predict(X_test)

errore = MSE(y_test, pred)
errore_sqr = RMSE(y_test, pred)
r2 = r2_score(y_test, pred)

print("R2 Score:", r2)
print("Mean Squared Error:", errore)
print("Root Mean Squared Error:", errore_sqr)
print()

ridge_coefs = pd.DataFrame({
    "feature": X_train.columns.values,
    "coef_ridge": regression.coef_
}).sort_values("coef_ridge", key=abs, ascending=False)

print("\nTop 10 coefficienti Ridge (per valore assoluto):")
print(ridge_coefs.head(10))

R2 Score: 0.6537743308021151
Mean Squared Error: 0.32936247849913336
Root Mean Squared Error: 0.5739011051558739


Top 10 coefficienti Ridge (per valore assoluto):
               feature  coef_ridge
437     SellerG_Darras    3.088803
458        SellerG_For    2.578129
485     SellerG_Hooper    2.291224
638  SellerG_Sotheby's    2.169579
474       SellerG_Hall    2.084042
672      SellerG_Weast    1.498503
564   SellerG_Nicholas    1.398948
390       SellerG_Blue    1.313658
662    SellerG_VICProp    1.268109
553   SellerG_Mindacom    1.107799

In [92]:
lasso_model = Lasso(alpha = 0.01)
lasso_model.fit(X_train, y_train)

y_pred_lasso = lasso_model.predict(X_test)
lasso_r2 = r2_score(y_test, y_pred_lasso)
lasso_mse = MSE(y_test, y_pred_lasso)
lasso_rmse = np.sqrt(lasso_mse)

print("\n===== RISULTATI LASSO =====")

print("R2 test:", round(lasso_r2, 4))
print("MSE test:", round(lasso_mse, 6))
print("RMSE test:", round(lasso_rmse, 4))

===== RISULTATI LASSO =====
R2 test: 0.5733
MSE test: 0.405879
RMSE test: 0.6371

In [98]:
ridge_model = Ridge(alpha = 20)
ridge_model.fit(X_train, y_train)

pred = ridge_model.predict(X_test)
ridge_r2 = r2_score(y_test, pred)
ridge_mse = MSE(y_test, pred)
ridge_rmse = np.sqrt(ridge_mse)

print("\n===== RISULTATI RIDGE =====")

print("R2 test:", round(ridge_r2, 4))
print("MSE test:", round(ridge_mse, 6))
print("RMSE test:", round(ridge_rmse, 4))

===== RISULTATI RIDGE =====
R2 test: 0.6611
MSE test: 0.322391
RMSE test: 0.5678

In [ ]:
# ==============================
# Ridge Regression
# ==============================

alphas_ridge = np.linspace(10, 25, 15)
ridge = RidgeCV(alphas=alphas_ridge, cv=5)
ridge.fit(X_train, y_train)

y_pred_ridge = ridge.predict(X_test)

ridge_r2 = r2_score(y_test, y_pred_ridge)
ridge_mse = MSE(y_test, y_pred_ridge)
ridge_rmse = np.sqrt(ridge_mse)

print("\n===== RISULTATI RIDGE =====")
print("Alpha scelto:", ridge.alpha_)
print("R2 test:", round(ridge_r2, 4))
print("MSE test:", round(ridge_mse, 6))
print("RMSE test:", round(ridge_rmse, 4))

ridge_coefs = pd.DataFrame({
    "feature": X_train.columns.values,
    "coef_ridge": ridge.coef_
}).sort_values("coef_ridge", key=abs, ascending=False)

print("\nTop 10 coefficienti Ridge (per valore assoluto):")
print(ridge_coefs.head(10))

===== RISULTATI RIDGE =====
Alpha scelto: 10.0
R2 test: 0.6621
MSE test: 0.321398
RMSE test: 0.5669

Top 10 coefficienti Ridge (per valore assoluto):
                  feature  coef_ridge
638     SellerG_Sotheby's    1.015883
474          SellerG_Hall    0.814419
220    Suburb_Middle Park    0.802799
68      Suburb_Canterbury    0.726086
351                Type_u   -0.709853
179   Suburb_Ivanhoe East    0.707791
506           SellerG_Kay    0.660939
48        Suburb_Brighton    0.565502
358  SellerG_Abercromby's    0.560686
121      Suburb_Eaglemont    0.540443

In [104]:
# ==============================
# Lasso Regression
# ==============================

alphas_lasso = np.logspace(-10, 100, 10)
lasso = LassoCV(alphas=alphas_ridge, cv=5)
lasso.fit(X_train, y_train)

y_pred_ridge = ridge.predict(X_test)

lasso_r2 = r2_score(y_test, y_pred_ridge)
lasso_mse = MSE(y_test, y_pred_ridge)
lasso_rmse = np.sqrt(ridge_mse)

print("\n===== RISULTATI RIDGE =====")
print("Alpha scelto:", ridge.alpha_)
print("R2 test:", round(lasso_r2, 4))
print("MSE test:", round(lasso_mse, 6))
print("RMSE test:", round(lasso_rmse, 4))

ridge_coefs = pd.DataFrame({
    "feature": X_train.columns.values,
    "coef_ridge": ridge.coef_
}).sort_values("coef_ridge", key=abs, ascending=False)

print("\nTop 10 coefficienti Ridge (per valore assoluto):")
print(ridge_coefs.head(10))

===== RISULTATI RIDGE =====
Alpha scelto: 10.0
R2 test: 0.6621
MSE test: 0.321398
RMSE test: 0.5669

Top 10 coefficienti Ridge (per valore assoluto):
                  feature  coef_ridge
638     SellerG_Sotheby's    1.015883
474          SellerG_Hall    0.814419
220    Suburb_Middle Park    0.802799
68      Suburb_Canterbury    0.726086
351                Type_u   -0.709853
179   Suburb_Ivanhoe East    0.707791
506           SellerG_Kay    0.660939
48        Suburb_Brighton    0.565502
358  SellerG_Abercromby's    0.560686
121      Suburb_Eaglemont    0.540443