In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import mean_squared_error as MSE

from sklearn.preprocessing import MinMaxScaler

In [3]:
df = pd.read_csv('california_housing_data.csv')

In [4]:
df.head(30)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
6,3.6591,52.0,4.931907,0.951362,1094.0,2.128405,37.84,-122.25,2.992
7,3.1200,52.0,4.797527,1.061824,1157.0,1.788253,37.84,-122.25,2.414
8,2.0804,42.0,4.294118,1.117647,1206.0,2.026891,37.84,-122.26,2.267
9,3.6912,52.0,4.970588,0.990196,1551.0,2.172269,37.84,-122.25,2.611
10,3.2031,52.0,5.477612,1.079602,910.0,2.263682,37.85,-122.26,2.815
11,3.2705,52.0,4.772480,1.024523,1504.0,2.049046,37.85,-122.26,2.418
12,3.0750,52.0,5.322650,1.012821,1098.0,2.346154,37.85,-122.26,2.135
13,2.6736,52.0,4.000000,1.097701,345.0,1.982759,37.84,-122.26,1.913
14,1.9167,52.0,4.262903,1.009677,1212.0,1.954839,37.85,-122.26,1.592
15,2.1250,50.0,4.242424,1.071970,697.0,2.640152,37.85,-122.26,1.400
16,2.7750,52.0,5.939577,1.048338,793.0,2.395770,37.85,-122.27,1.525
17,2.1202,52.0,4.052805,0.966997,648.0,2.138614,37.85,-122.27,1.555
18,1.9911,50.0,5.343675,1.085919,990.0,2.362768,37.84,-122.26,1.587
19,2.6033,52.0,5.465455,1.083636,690.0,2.509091,37.84,-122.27,1.629
20,1.3578,40.0,4.524096,1.108434,409.0,2.463855,37.85,-122.27,1.475
21,1.7135,42.0,4.478142,1.002732,929.0,2.538251,37.85,-122.27,1.598
22,1.7250,52.0,5.096234,1.131799,1015.0,2.123431,37.84,-122.27,1.139
23,2.1806,52.0,5.193846,1.036923,853.0,2.624615,37.84,-122.27,0.997
24,2.6000,52.0,5.270142,1.035545,1006.0,2.383886,37.84,-122.27,1.326
25,2.4038,41.0,4.495798,1.033613,317.0,2.663866,37.85,-122.28,1.075
26,2.4597,49.0,4.728033,1.020921,607.0,2.539749,37.85,-122.28,0.938
27,1.8080,52.0,4.780856,1.060453,1102.0,2.775819,37.85,-122.28,1.055
28,1.6424,50.0,4.401691,1.040169,1131.0,2.391121,37.84,-122.28,1.089
29,1.6875,52.0,4.703226,1.032258,395.0,2.548387,37.84,-122.28,1.320

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

**train test split**
\nEstraggo le features e il target (prezzo mediano) dal data frame e divido in train e test con una rapporto 80:30.

In [6]:
X = df[df.columns[:-2]]
y = np.array(df['MedHouseVal'])
X

       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
...       ...       ...       ...        ...         ...       ...       ...
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

[20640 rows x 7 columns]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [8]:
print(X_train)

       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude
7061   4.1312      35.0  5.882353   0.975490      1218.0  2.985294     33.93
14689  2.8631      20.0  4.401210   1.076613       999.0  2.014113     32.79
17323  4.2026      24.0  5.617544   0.989474       731.0  2.564912     34.59
10056  3.1094      14.0  5.869565   1.094203       302.0  2.188406     39.26
15750  3.3068      52.0  4.801205   1.066265      1526.0  2.298193     37.77
...       ...       ...       ...        ...         ...       ...       ...
11284  6.3700      35.0  6.129032   0.926267       658.0  3.032258     33.78
11964  3.0500      33.0  6.868597   1.269488      1753.0  3.904232     34.02
5390   2.9344      36.0  3.986717   1.079696      1756.0  3.332068     34.03
860    5.7192      15.0  6.395349   1.067979      1777.0  3.178891     37.58
15795  2.5755      52.0  3.402576   1.058776      2619.0  2.108696     37.77

[14448 rows x 7 columns]

Normalizzazione riportando a media 0 e var 1.

In [9]:
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)
X_test_s

array([[-1.1526893 , -0.28346293, -0.50781822, ..., -0.03151006,
         0.06127763,  0.19166399],
       [-0.70640568,  0.11294728, -0.16252032, ...,  0.1202196 ,
        -0.03551561, -0.23911452],
       [-0.20830675,  1.85715216, -0.59546738, ..., -0.10342817,
        -0.14215427,  1.00639726],
       ...,
       [-0.19155996, -0.99700129, -0.6830438 , ...,  3.14516537,
        -0.06058827, -0.92742367],
       [-0.11911302, -1.47269353,  0.02607207, ...,  3.95292851,
         0.03461374,  1.01576201],
       [-0.43304974, -0.91771925, -0.84872893, ...,  2.35757439,
        -0.0407528 , -0.70266966]])

In [10]:
y_train_s = scaler.fit_transform(y_train.reshape(-1,1)).flatten()
y_test_s = scaler.transform(y_test.reshape(-1,1)).flatten()

In [11]:
regression = LinearRegression()

regression.fit(X_train_s, y_train_s)

LinearRegression()

In [12]:
y_pred_s = regression.predict(X_test_s)

In [13]:
errore = MSE(y_test_s, y_pred_s)

print("Mean Squared Error (su variabbili standardizzate):", errore)

y_pred = scaler.inverse_transform(y_pred_s.reshape(-1,1)).flatten()

errore = MSE(y_test, y_pred)

print("Mean Squared Error:", errore)

Mean Squared Error (su variabbili standardizzate): 0.4563416008651703
Mean Squared Error: 0.6113590070321648

**regressione senza normalizzare i target**

In [14]:
regression.fit(X_train_s, y_train)
pred = regression.predict(X_test_s)
errore = MSE(y_test, pred )

print("Mean Squared Error:", errore)

Mean Squared Error: 0.6113590070321648

Normalizzare o meno il target non altera le prestazioni, in effetti in valore assoluto non è molto grande.

In [15]:
print(f"La media dil prezzo delle case nel test set è: {np.mean(y_test):.3f}, la deviazione standard è: {np.std(y_test):.3f}, il valore massimo è: {np.max(y_test):.3f} e il valore minimo è: {np.min(y_test):.3f}")
print(f"la media del prezzo nel train set predetto è: {np.mean(y_train):.3f}, la deviazione standard è: {np.std(y_train):.3f}, il valore massimo è: {np.max(y_train):.3f} e il valore minimo è: {np.min(y_train):.3f}")
print(f"la media del prezzo nel test set predetto è: {np.mean(y_pred):.3f}, la deviazione standard è: {np.std(y_pred):.3f}, il valore massimo è: {np.max(y_pred):.3f} e il valore minimo è: {np.min(y_pred):.3f}")

La media dil prezzo delle case nel test set è: 2.067, la deviazione standard è: 1.146, il valore massimo è: 5.000 e il valore minimo è: 0.150
la media del prezzo nel train set predetto è: 2.069, la deviazione standard è: 1.157, il valore massimo è: 5.000 e il valore minimo è: 0.150
la media del prezzo nel test set predetto è: 2.066, la deviazione standard è: 0.848, il valore massimo è: 10.753 e il valore minimo è: -0.296

**Normalizzazione fra 0 e 1**

In [16]:
scaler = MinMaxScaler()
X_train_s = scaler.fit_transform(X_train) 
X_test_s = scaler.transform(X_test)

In [17]:
regression.fit(X_train_s, y_train)
pred = regression.predict(X_test_s)
errore = MSE(y_test, pred)

print("Mean Squared Error:", errore)

Mean Squared Error: 0.6113590070321644

**Outliers**

In [18]:
for col in df.columns:
    # 1. Calcolo dei Quartili
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    # 2. Definizione dei limiti
    lower_bound = Q1 - 1.5 * IQR 
    upper_bound = Q3 + 1.5 * IQR

    print(f"Intervallo 'Normale' per {col}: da {lower_bound:.2f} a {upper_bound:.2f}")

    # 3. Individuazione degli Outlier
    outliers_iqr = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f"Numero di Outlier rilevati con IQR: {len(outliers_iqr)}")
    print(f"Percentuale sul totale: {len(outliers_iqr)/len(df)*100:.2f}%")

    # Vediamo alcuni di questi outlier estremi
    print("\nEsempi di outlier estremi:")
    print(outliers_iqr[col].sort_values(ascending=False).head(5))
    
    print()
    print("-" * 50)

Intervallo 'Normale' per MedInc: da -0.71 a 8.01
Numero di Outlier rilevati con IQR: 681
Percentuale sul totale: 3.30%

Esempi di outlier estremi:
1566     15.0001
17858    15.0001
17170    15.0001
17108    15.0001
17107    15.0001
Name: MedInc, dtype: float64

--------------------------------------------------
Intervallo 'Normale' per HouseAge: da -10.50 a 65.50
Numero di Outlier rilevati con IQR: 0
Percentuale sul totale: 0.00%

Esempi di outlier estremi:
Series([], Name: HouseAge, dtype: float64)

--------------------------------------------------
Intervallo 'Normale' per AveRooms: da 2.02 a 8.47
Numero di Outlier rilevati con IQR: 511
Percentuale sul totale: 2.48%

Esempi di outlier estremi:
1914     141.909091
1979     132.533333
12447     62.422222
1913      61.812500
11862     59.875000
Name: AveRooms, dtype: float64

--------------------------------------------------
Intervallo 'Normale' per AveBedrms: da 0.87 a 1.24
Numero di Outlier rilevati con IQR: 1424
Percentuale sul totale: 6.90%

Esempi di outlier estremi:
1979     34.066667
1914     25.636364
11862    15.312500
12447    14.111111
9676     11.410714
Name: AveBedrms, dtype: float64

--------------------------------------------------
Intervallo 'Normale' per Population: da -620.00 a 3132.00
Numero di Outlier rilevati con IQR: 1196
Percentuale sul totale: 5.79%

Esempi di outlier estremi:
15360    35682.0
9880     28566.0
13139    16305.0
10309    16122.0
6057     15507.0
Name: Population, dtype: float64

--------------------------------------------------
Intervallo 'Normale' per AveOccup: da 1.15 a 4.56
Numero di Outlier rilevati con IQR: 711
Percentuale sul totale: 3.44%

Esempi di outlier estremi:
19006    1243.333333
3364      599.714286
16669     502.461538
13034     230.172414
9172       83.171429
Name: AveOccup, dtype: float64

--------------------------------------------------
Intervallo 'Normale' per Latitude: da 28.26 a 43.38
Numero di Outlier rilevati con IQR: 0
Percentuale sul totale: 0.00%

Esempi di outlier estremi:
Series([], Name: Latitude, dtype: float64)

--------------------------------------------------
Intervallo 'Normale' per Longitude: da -127.48 a -112.33
Numero di Outlier rilevati con IQR: 0
Percentuale sul totale: 0.00%

Esempi di outlier estremi:
Series([], Name: Longitude, dtype: float64)

--------------------------------------------------
Intervallo 'Normale' per MedHouseVal: da -0.98 a 4.82
Numero di Outlier rilevati con IQR: 1071
Percentuale sul totale: 5.19%

Esempi di outlier estremi:
20443    5.00001
89       5.00001
20436    5.00001
459      5.00001
20427    5.00001
Name: MedHouseVal, dtype: float64

--------------------------------------------------

In [29]:
df["MedInc"].quantile(0.15)
df["MedInc"].quantile(1)

np.float64(15.0001)

In [40]:
for col in df.columns:
    # 1. Calcolo dei Quartili
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    # 2. Definizione dei limiti
    lower_bound = Q1 - 1.5 * IQR 
    upper_bound = Q3 + 1.5 * IQR
    
    mask = (df[col] < lower_bound) | (df[col] > upper_bound)
    df = df[~mask] #drop degli outlier

In [41]:
X = df[df.columns[:-2]]
y = np.array(df['MedHouseVal'])

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [43]:
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

In [44]:
regression.fit(X_train_s, y_train)
pred = regression.predict(X_test_s)
errore = MSE(y_test, pred)

print("Mean Squared Error:", errore)

Mean Squared Error: 0.3432112250599951

IL MSE è migliorato rispetto a prima di rimuovere gli outlier